### ISSUE TITLE
接口文档中有formData类型的入参，生成的代码里面没有这个参数。

### ISSUE THREAD

**Issue by wou101771** [huajiayi/openapi-tool#5]
![image](https://user-images.githubusercontent.com/52279380/218781740-6ed59f1e-6088-4b97-a0e6-88c8e67ab9f6.png)

生成的代码
![image](https://user-images.githubusercontent.com/52279380/218781960-c047c8a7-8384-4c00-a610-c2d665a2d087.png)

**Comment by huajiayi** [comment]
已修复
