### ISSUE TITLE
get请求的参数类型同时有path和query，生产的接口函数url里面没有拼接上path

### ISSUE THREAD

**Issue by wou101771** [huajiayi/openapi-tool#6]
接口文档
![image](https://user-images.githubusercontent.com/52279380/218916477-9a889f74-c87a-4644-a46c-a1742c7f44a5.png)

代码
![image](https://user-images.githubusercontent.com/52279380/218916530-653768f7-0e1e-44c3-a8e7-08fb4928534e.png)

**Comment by huajiayi** [comment]
测试后没有发现问题，请检查后端path是否填写正确
